<?php
/**
 * @file
 * Search api glossary module file.
 */

use Drupal\Core\Field\BaseFieldDefinition;

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Entity\EntityTypeInterface;


/**
 * Implements hook_entity_base_field_info.
 */
function search_api_glossary_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  // Load up config and loop though settings.
  $config = \Drupal::config('search_api_glossary.settings');
  $search_api_glossary_settings = $config->get();

  if (!empty($search_api_glossary_settings)) {
    // Loop through the saved config from
    // Search API field settings form.
    foreach ($search_api_glossary_settings as $key => $value) {
      $glossary_field_id = 'field_glossaryaz_' . $value['entity_type'] . '_' . $value['field_name'];
      $glossary_field_name = $value['label'] . ' Glossary';
      $glossary_field_desc = 'Glossary field for ' . $value['label'] . '.';

      // Create the fields.
      if ($entity_type->id() == $value['entity_type']) {
        $fields = array();
        $fields[$glossary_field_id] = BaseFieldDefinition::create('string')
          ->setLabel(t($glossary_field_name))
          ->setDescription(t($glossary_field_desc))
          ->setTranslatable(FALSE)
          ->setRevisionable(FALSE)
          ->setSetting('max_length', 3)
          ->setReadOnly(TRUE)
          ->setComputed(TRUE)
          ->setDefaultValue('');
        return $fields;
      }
    }
  }

}


/**
 * Implements hook_search_api_index_items_alter.
 */
function search_api_glossary_search_api_index_items_alter(\Drupal\search_api\IndexInterface $index, array &$items) {
  foreach ($items as $item) {
    // Get values from source field.
    // @TODO Maybe step through the array for value
    $source_field_value = $item->getField('title')->getValues()[0];

    // Glossary process
    $glossary_value = search_api_glossary_glossary_getter($source_field_value);

    // @TODO Check if the glossary fields exisit
    // Set the title.
    //$item->getField('mymodule_text')->addValue($glossary_value);
  }
}


/**
 * Getter callback for title_az_glossary property.
 */
function search_api_glossary_glossary_getter($source_value) {
  $first_letter = strtoupper($source_value)[0];
  return search_api_glossary_glossary_getter_helper($first_letter, array());
}

/**
 * Getter Helper for Alpha Numeric Keys.
 */
function search_api_glossary_glossary_getter_helper($first_letter, $glossary_az_grouping) {
  $key = $first_letter;

  // Is it Alpha?
  // Do we have Alpha grouping?
  if (ctype_alpha($first_letter) && in_array('glossary_az_grouping_az', $glossary_az_grouping)) {
    $first_letter = "A-Z";
  }
  // Is it a number?
  // Do we have Numeric grouping?
  elseif (ctype_digit($first_letter) && in_array('glossary_az_grouping_09', $glossary_az_grouping)) {
    $first_letter = "0-9";
  }
  // Catch non alpha numeric.
  // Do we have Non Alpha Numeric grouping?
  elseif (in_array('glossary_az_grouping_other', $glossary_az_grouping)) {
    $first_letter = "#";
  }

  // All done, return the key
  return $first_letter;
}







/**
 * Add search_api_glossary settings to Search API Index configuration.
 * Implements hook_form_FORM_ID_alter()
 * @see \Drupal\search_api\Form\IndexFieldsForm method buildForm at /modules/search_api/src/Form/IndexFieldsForm.php
 */
function search_api_glossary_form_search_api_index_fields_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::config('search_api_glossary.settings');
  $entity = $form_state->getFormObject()->getEntity();

  // @TODO Check if there are any limitations,
  // If not, maybe expand this in future.
  $allowed_field_types = array(
    'integer',
    'text',
    'string',
  );

  foreach ($entity->getDatasources() as $datasource_id => $datasource) {
    $fields = $entity->getFieldsByDatasource($datasource_id);

    foreach ($fields as $field) {
      $field_settings_array = $field->getSettings();

      $datasource_id = $field_settings_array['datasource_id'];
      $datasource_id_clean = str_replace('entity:', '', $datasource_id);
      $field_name = $field_settings_array['property_path'];
      $field_label = $field_settings_array['label'];
      $field_type = $field_settings_array['type'];
      $locked = $field->isTypeLocked();

      // Identify glossary fields and skip them.
      // Glossary field should be excluded always.
      // @TODO Glossary field TYPE should always be STRING.
      // Make it default and prevent changing.
      if (substr($field_name, 0, strlen('field_glossaryaz')) !== 'field_glossaryaz') {
        if (!$locked && in_array($field_type, $allowed_field_types)) {
          $form[$datasource_id]['fields'][$field_name]['glossary_az'] = array(
            '#type' => 'checkbox',
            '#title' => t('Enable'),
            '#default_value' => $config->get($field_name)['enabled'],
          );

          // Array to identify which header(s) to alter.
          $datasource_ids[$datasource_id] = $datasource_id;
        }

      }
    }
  }

  // Add glossary header to each fieldset.
  foreach ($datasource_ids as $datasource_id_unique) {
    $form[$datasource_id_unique]['#header'][] = t('Glossary AZ');
  }

  // Add a custom submit handler to save the array of types back to the config file.
  $form['actions']['submit']['#submit'][] = 'search_api_glossary_search_api_index_fields_submit';

}


function search_api_glossary_search_api_index_fields_submit($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $fields = $values['fields'];

  $entity = $form_state->getFormObject()->getEntity();
  $field_settings_array = $entity->get('field_settings');

  $config = \Drupal::configFactory()->getEditable('search_api_glossary.settings');

  foreach ($fields as $field_name => $field_values) {
    $entity_type_clean = str_replace('entity:', '', $field_settings_array[$field_name]['datasource_id']);

    if (isset($field_values['glossary_az']) && $field_values['glossary_az'] == 1) {
      $config_values = array(
        'enabled' => $field_values['glossary_az'],
        'entity_type' => $entity_type_clean,
        'field_type' => $field_values['type'],
        'field_name' => $field_name,
        'label' => $field_settings_array[$field_name]['label'],
      );

      // Set the variables.
      $config->set($field_name, $config_values)->save();
    }
    else {
      // Clear the unused variable choices.
      $config->clear($field_name)->save();
    }

    // @TODO Somehow mark the removed fields,
    // so they can be removed in
    // hook_entity_base_field_info().
    // Maybe hook into field remove?
  }

  // @TODO
  // clear caches


}
