search_api_glossary.settings:
  type: config_object
  label: 'Search API Glossary Settings'
  mapping:
    group_prefix:
      type: mapping
      label: 'Group Prefix'
      mapping:
        alpha:
          type: string
          label: 'Alpha Group Prefix'
        numeric:
          type: string
          label: 'Numeric Group Prefix'
        special:
          type: string
          label: 'Special Group Prefix'
